filter:
    excluded_paths:
        - 'library/tiqr/tests/*'
        - 'TestServer/*'

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php: {  }
    
build:
    environment:
        apt_packages:
          - libcurl
        php: 7.2
        pecl_extensions:
          - intl
          - gmp
    dependencies:
        override:
            - composer install --no-interaction --no-scripts --ignore-platform-req
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: XDEBUG_MODE=coverage; ./vendor/bin/phpunit --configuration=./ci/qa/qa-config/phpunit.xml
                      coverage:
                          file: ./ci/qa/qa-config/coverage.xml
                          format: clover
