filter:
    excluded_paths:
        - 'library/tiqr/tests/*'

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php: {  }
    
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
