filter:
    excluded_paths:
        - 'library/tiqr/tests/*'
        - 'TestServer/*'

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php: {  }
    
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                environment:
                    php:
                        version: 7.2
                override:
                    - command: XDEBUG_MODE=coverage; ./vendor/bin/phpunit
                      coverage:
                          file: coverage.xml
                          format: clover
