filter:
    excluded_paths:
        - 'library/tiqr/tests/*'
        - 'TestServer/*'

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php: {  }
    
build:
    # Use bionic image instead of the default trusty image so we can meet the pushok dependency on curl >=7.46.0
    image: default-bionic
    environment:
        php: 8.2

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration=./ci/qa/qa-config/phpunit.xml
                      coverage:
                          file: ./ci/qa/qa-config/coverage.xml
                          format: clover
