language: php

php:
  - 7.2

before_install:
  - sudo apt-get -y install libxml2-dev

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit -c ./phpunit.xml
  - wget -q https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -O local-php-security-checker && chmod +x ./local-php-security-checker && ./local-php-security-checker
