language: php

php:
  - 7.2

before_install:
  - sudo apt-get -y install libxml2-dev

install:
  - travis_retry composer install --no-interaction

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text
