name: test-integration
on:
  pull_request:
  push:
    branches: [ master, develop ]
jobs:
  run-qa-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /var/www/html/
    container:
      image:  ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
      volumes:
        - .:/var/www/html
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install

      - name: Run test scripts (allowed to fail)
        run: composer static-analysis

      - name: Run test scripts
        run: composer phpunit && composer security-tests

      - name: Output log files on failure
        if: failure()
        run: tail -2000 /var/log/syslog
