name: test-integration
on:
  pull_request:
  push:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Init environment
        run: cd ci/docker && docker-compose up -d
      - name: Install dependencies
        run: cd ci/docker && docker-compose exec -T tiqr-server-libphp bash -lc 'composer install'
      - name: Run test scripts (allowed to fail)
        run: cd ci/docker && docker-compose exec -T tiqr-server-libphp bash -lc 'composer static-analysis'
      - name: Run test scripts
        run: cd ci/docker && docker-compose exec -T tiqr-server-libphp bash -lc 'composer phpunit && composer security-tests'
      - name: Output log files on failure
        if: failure()
        run: tail -2000 /var/log/syslog
